### ISSUE TITLE
End to End with Factor Graph and Back

### ISSUE THREAD

**Issue by tsaience** [vramesh/factor-graph-compute#11]

**Comment by vramesh** [comment]
@suchanv you should try to make a test that corresponds to a simple factor graph and operation such as pagerank, svd, k-means - your choice

**Comment by vramesh** [comment]
@suchanv this might help you with trying mocks: https://blog.fugue.co/2016-02-11-python-mocking-101.html

that way you don't need to wait for other components to be done. I implemented mocks in my unit tests you can take a look
